import { Play, LayoutGrid, BookOpen, Stethoscope } from 'lucide-react'

export const CATEGORIES = [
    {
        id: 'video',
        code: 'BV',
        label: 'Video',
        longLabel: 'Best Video Session',
        icon: Play,
        count: 12,
        color: 'bg-violet-50 border-violet-200 text-violet-700',
        iconBg: 'bg-violet-100',
        iconColor: 'text-violet-600',
        dotColor: 'bg-violet-500',
        accent: '#7c3aed',
        description: 'Surgical technique videos demonstrating innovative urological procedures, live surgery recordings, and step-by-step operative demonstrations.',
        downloadUrl: 'https://1d2b4dea-e0f6-42cc-87ed-25777b45da4f.usrfiles.com/ugd/1d2b4d_ab61dcb331984fc3a7e757ec4b0dd3c0.pdf',
        highlights: ['Robotic surgery', 'Laparoscopic techniques', 'Endourology', 'Reconstructive procedures'],
    },
    {
        id: 'podium',
        code: 'BP',
        label: 'Podium',
        longLabel: 'Best Paper Session',
        icon: Stethoscope,
        count: 18,
        color: 'bg-fun-blue-50 border-fun-blue-200 text-fun-blue-700',
        iconBg: 'bg-fun-blue-100',
        iconColor: 'text-fun-blue-600',
        dotColor: 'bg-fun-blue-500',
        accent: '#185fa5',
        description: 'Oral presentations of original research, randomised controlled trials, and clinical studies selected for podium presentation at NZUSICON 2025.',
        downloadUrl: '#',
        highlights: ['RCTs', 'Clinical outcomes', 'Epidemiology', 'New techniques'],
    },
    {
        id: 'poster',
        code: 'BPos',
        label: 'Posters',
        longLabel: 'Moderated Poster Session',
        icon: LayoutGrid,
        count: 24,
        color: 'bg-emerald-50 border-emerald-200 text-emerald-700',
        iconBg: 'bg-emerald-100',
        iconColor: 'text-emerald-600',
        dotColor: 'bg-emerald-500',
        accent: '#059669',
        description: 'Moderated poster presentations covering a broad range of urological topics, reviewed and discussed by expert faculty during dedicated poster sessions.',
        downloadUrl: '#',
        highlights: ['Case series', 'Pilot studies', 'QI projects', 'Technology'],
    },
    {
        id: 'unmoderated',
        code: 'UPos',
        label: 'e-Posters',
        longLabel: 'Unmoderated e-Poster Session',
        icon: BookOpen,
        count: 31,
        color: 'bg-amber-50 border-amber-200 text-amber-700',
        iconBg: 'bg-amber-100',
        iconColor: 'text-amber-600',
        dotColor: 'bg-amber-500',
        accent: '#d97706',
        description: 'Electronic poster submissions displayed throughout the conference. Authors present at designated times for attendee interaction and discussion.',
        downloadUrl: '#',
        highlights: ['Case reports', 'Observational studies', 'Reviews', 'Audits'],
    },
]