export const ALL_EVENTS = [
    {
        id: 1,
        index: "01",
        title: "Online Academic Series",
        subtitle: "NZUSI Webinar Programme",
        date: "Jan 11, 2026",
        dateShort: "11 Jan",
        month: "JAN",
        day: "11",
        location: "Online / Zoom",
        type: "NZUSI",
        category: "Academic",
        tag: "Completed",
        highlight: false,
        attendees: "120+",
        description: "Monthly online academic series covering latest urology literature, case reviews, and clinical updates for North Zone members.",
        link: "#",
    },
    {
        id: 2,
        index: "02",
        title: "Mid-term CME",
        subtitle: "Karnal Chapter",
        date: "Apr 24–25, 2026",
        dateShort: "24 Apr",
        month: "APR",
        day: "24",
        location: "Karnal, Haryana",
        type: "NZUSI",
        category: "CME",
        tag: "Upcoming",
        highlight: true,
        attendees: "200+",
        description: "Two-day continuing medical education programme with hands-on workshops, expert lectures, and case presentations hosted by the Karnal Chapter.",
        link: "#",
    },
    {
        id: 3,
        index: "03",
        title: "USICON 2026",
        subtitle: "Annual National Conference",
        date: "Jun 12–14, 2026",
        dateShort: "12 Jun",
        month: "JUN",
        day: "12",
        location: "Mumbai, Maharashtra",
        type: "USI",
        category: "Conference",
        tag: "Upcoming",
        highlight: false,
        attendees: "1500+",
        description: "The annual national conference of the Urological Society of India, bringing together urologists from across the country.",
        link: "#",
    },
    {
        id: 4,
        index: "04",
        title: "Youth Conclave",
        subtitle: "North Zone",
        date: "Aug 22–23, 2026",
        dateShort: "22 Aug",
        month: "AUG",
        day: "22",
        location: "New Delhi",
        type: "NZUSI",
        category: "Conclave",
        tag: "Upcoming",
        highlight: false,
        attendees: "300+",
        description: "Dedicated platform for young urologists and trainees to present research, attend skill workshops, and network with senior faculty.",
        link: "#",
    },
    {
        id: 5,
        index: "05",
        title: "Endourology Society Meeting",
        subtitle: "Annual Symposium",
        date: "Sep 18–20, 2026",
        dateShort: "18 Sep",
        month: "SEP",
        day: "18",
        location: "Chandigarh, Punjab",
        type: "USI",
        category: "Conference",
        tag: "Upcoming",
        highlight: false,
        attendees: "400+",
        description: "Annual scientific meeting of the Endourology Society covering minimally invasive urology, laser techniques, and robotic surgery.",
        link: "#",
    },
    {
        id: 6,
        index: "06",
        title: "NZUSICON 2026",
        subtitle: "Annual Congress — Amritsar",
        date: "Nov 27–29, 2026",
        dateShort: "27 Nov",
        month: "NOV",
        day: "27",
        location: "Amritsar, Punjab",
        type: "NZUSI",
        category: "Conference",
        tag: "Flagship",
        highlight: true,
        attendees: "600+",
        description: "The flagship annual congress of the North Zone chapter — three days of keynotes, live surgeries, industry exhibitions, workshops, and the prestigious NZUSI Awards ceremony.",
        link: "/files/NZ-USICON-REGISTRATION-FORM.pdf",
    },
]